services:
  db:
    image: postgres:16
    container_name: musclub_pg
    environment:
      POSTGRES_DB: musclub
      POSTGRES_USER: musclub
      POSTGRES_PASSWORD: musclub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musclub -d musclub"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
